### ISSUE TITLE
clicked on "graph", but "The requested resource could not be found."

### ISSUE THREAD

**Issue by wdebeaum** [mrmechko/stripsWiki#4]
When I click on "graph" in the top right corner, I get just a white page saying "The requested resource could not be found."

**Comment by mrmechko** [comment]
It needs a form.  I'll get on that after I finish the git backend for the wiki files.  currently, you can go to /graph/[some word here] and it gives you a visualization of the wordnet-trips mappings for that word.

**Comment by wdebeaum** [comment]
Maybe if I'm on the browse page for a word, clicking on "graph" should just go directly to the graph for that word, instead of trying to go to the not-yet-existing form?

**Comment by mrmechko** [comment]
I can do that.  Warning, I haven't actually made a page for graph yet.  It just dumps the javascript for displaying the graph and that's the whole page.

**Comment by mrmechko** [comment]
update: clicking on graph takes you to the graph of whatever is in the text box.
