### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by wdebeaum** [mrmechko/stripsWiki#7]
I tried to run this on the same VM as Omid's stuff, but I got "java.lang.OutOfMemoryError: Java heap space" coming from SWordNet. The VM doesn't have a lot of memory (2.5GB), and Omid's stuff is using most of it. Would it be better to put it on a separate VM? Is 2.5GB enough?

**Comment by mrmechko** [comment]
*ref in person conversation

The full system takes about 2-ish GB to run.  Probably need a new VM

**Comment by wdebeaum** [comment]
The new VM has 1895MB free with nothing running (I even turned off X11). I watched it go down to about 1440MB before java complained that it was "out of memory". That difference seems suspiciously close to the default heap size for java, so I tried setting `JAVA_OPTS=-Xmx2g`, but that had no effect. Here's the stack trace in case you're interested:

```
wikiJVM loading from /home/wdebeaum/mrmechko/flaming-tyrion/lexicon/data/
wikiJVM[ERROR] java.lang.OutOfMemoryError: Java heap space
wikiJVM[ERROR]   at scala.collection.mutable.ResizableArray$class.$init$(ResizableArray.scala:32)
wikiJVM[ERROR]   at scala.collection.mutable.ArrayBuffer.<init>(ArrayBuffer.scala:49)
wikiJVM[ERROR]   at scala.collection.mutable.ArrayBuffer.<init>(ArrayBuffer.scala:63)
wikiJVM[ERROR]   at scala.collection.mutable.ArrayBuffer$.newBuilder(ArrayBuffer.scala:191)
wikiJVM[ERROR]   at scala.collection.generic.GenericTraversableTemplate$class.newBuilder(GenericTraversableTemplate.scala:65)
wikiJVM[ERROR]   at scala.collection.AbstractTraversable.newBuilder(Traversable.scala:104)
wikiJVM[ERROR]   at scala.collection.TraversableLike$$anonfun$groupBy$1$$anonfun$1.apply(TraversableLike.scala:333)
wikiJVM[ERROR]   at scala.collection.TraversableLike$$anonfun$groupBy$1$$anonfun$1.apply(TraversableLike.scala:333)
wikiJVM[ERROR]   at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
wikiJVM[ERROR]   at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
wikiJVM[ERROR]   at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:333)
wikiJVM[ERROR]   at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:331)
wikiJVM[ERROR]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
wikiJVM[ERROR]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
wikiJVM[ERROR]   at scala.collection.TraversableLike$class.groupBy(TraversableLike.scala:331)
wikiJVM[ERROR]   at scala.collection.AbstractTraversable.groupBy(Traversable.scala:104)
wikiJVM[ERROR]   at com.github.mrmechko.swordnet.SWordNet$.<init>(swordnet.scala:57)
wikiJVM[ERROR]   at com.github.mrmechko.swordnet.SWordNet$.<clinit>(swordnet.scala)
wikiJVM[ERROR]   at com.github.mrmechko.swordnet.structures.SKey$.get(SKey.scala:61)
wikiJVM[ERROR]   at strips.ontology.SOntology.strips$ontology$SOntology$$testWN(Ontology.scala:11)
wikiJVM[ERROR]   at strips.ontology.SOntology$$anonfun$2.apply(Ontology.scala:34)
wikiJVM[ERROR]   at strips.ontology.SOntology$$anonfun$2.apply(Ontology.scala:34)
wikiJVM[ERROR]   at scala.collection.immutable.List.foreach(List.scala:381)
wikiJVM[ERROR]   at strips.ontology.SOntology.<init>(Ontology.scala:34)
wikiJVM[ERROR]   at wiki.Server$.<init>(server.scala:160)
wikiJVM[ERROR]   at wiki.Server$.<clinit>(server.scala)
wikiJVM[ERROR]   at wiki.Server.main(server.scala)
wikiJVM[ERROR]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
wikiJVM[ERROR]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
wikiJVM[ERROR]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
wikiJVM[ERROR]   at java.lang.reflect.Method.invoke(Method.java:497)
wikiJVM[ERROR]   at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
wikiJVM ... finished with exit code 1
```

**Comment by mrmechko** [comment]
http://stackoverflow.com/questions/15280839/how-to-set-heap-size-for-sbt

This might help.  It seems that sbt ignores the jvm options and applies its own. 

some variation of the following in `build.sbt` could also solve it.  On a bus at the moment so I can't make this change myself.

```
javaOptions in run += "-Xmx4G"

javaOptions in run += "-Xms3G"

javaOptions in run +="-XX:+UseConcMarkSweepGC"
```

**Comment by wdebeaum** [comment]
I switched to `SBT_OPTS=-Xmx2g`, same result.

**Comment by mrmechko** [comment]
Any chance I could log in to the vm directly?

**Comment by mrmechko** [comment]
I just pushed a potential fix.  could you try pulling and redeploying?  If that doesn't work, could you post the results of running `sbt last`?

**Comment by mrmechko** [comment]
I also made a small update to `swordnet` to load only the necessary indexes into memory (particularly, I don't need the synset-offset index in this case).  you need to run `sbt update` to get the new version, but about 15 minutes after the time of this post.  This is an incomplete solution.

**Comment by wdebeaum** [comment]
I did `git pull` and `./runme.sh` in stripsWiki, and that seems to have fixed the memory issue. But now when I go to [the site](http://trips.ihmc.us/stripswiki/), I only get a blank blue page. It seems like it's using some absolute instead of relative paths, so they're referring to resources that don't exist on trips.ihmc.us. Right now I'm forwarding `/stripswiki/` on trips.ihmc.us to `/` on your server. I can change that to forward to `/stripswiki/` (or anything else, really) if that helps. Do you still want me to do `sbt last`, or was that only for the memory issue?

Re: logging in to the VM directly, you'd need to VPN into the IHMC network, which I'm guessing you don't have credentials for (Omid didn't).

**Comment by mrmechko** [comment]
yes please give me the `sbt last`.  It seems that the javascript hasn't compiled or been served.  The other paths seem to be working.

Could you also try running `sbt clean update compile ~re-start`

**Comment by wdebeaum** [comment]
I posted the output of those two commands in slack. I still only get a blank blue page. I think the JavaScript isn't being served because the initial page has the wrong URL for it: `<script type="text/javascript" src="/client-fastopt.js">`. That will attempt to fetch `client-fastopt.js` from trips.ihmc.us instead of your server, since it's an absolute path (starts with `/`) and lacks the `/stripswiki/` prefix that triggers the forwarding. I also see this bogus-looking URL: `//cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js` (I'm guessing there's supposed to be an `http:` at the beginning).

**Comment by mrmechko** [comment]
re bogus looking url: http://www.paulirish.com/2010/the-protocol-relative-url/

re forwarding: I'll have to figure it out, because I'm pretty sure that none of the ajax calls from the html side actually use the prefix.

**Comment by mrmechko** [comment]
check the latest commit.  There may be some dead links.

**Comment by wdebeaum** [comment]
Did `git pull` and `sbt clean update compile ~re-start` again, same problem.

**Comment by mrmechko** [comment]
I pushed another fix.  I accidentally prepended the baseurl to the actual javascript call rather than the script source.

**Comment by wdebeaum** [comment]
OK, now the script tag in question says `<script type="text/javascript" src="stripswiki/client-fastopt.js">`, which means it's trying to fetch `http://trips.ihmc.us/stripswiki/stripswiki/client-fastopt.js`, which probably isn't right.

**Comment by mrmechko** [comment]
hmm before it was trying to fetch `trips.imc.us/client-fastopt.js`
